CERNDocumentServer/cds-dojson

cds_dojson/marc21/fields/default/bd9xx.py

marc21: custom tag 980 addition

---

.travis.yml
cds_dojson/query.py
requirements-dev.txt
setup.py

query: externalize MatchUnit

---

cds_dojson/version.py

Signed-off-by: Esteban J. G. Gabancho <esteban.gabancho@gmail.com>

version: post-release bump

---

cds_dojson/schemas/deposits/records/project-v1.0.0.json
cds_dojson/schemas/records/project-v1.0.0.json

Signed-off-by: Nikos Filippakis <nikolaos.filippakis@cern.ch>

schemas: project schemas for multiple records per deposit

---

cds_dojson/schemas/records/base-v1.0.0.json
cds_dojson/schemas/records/project-v1.0.0.json
cds_dojson/schemas/records/video-v1.0.0.json

schemas: fox record video owners

---

cds_dojson/schemas/records/base-v1.0.0.json
cds_dojson/schemas/records/project-v1.0.0.json
cds_dojson/schemas/records/video-v1.0.0.json

schemas: remove "_access" from required fields

---

cds_dojson/schemas/deposits/records/project-v1.0.0.json
cds_dojson/schemas/deposits/records/video-v1.0.0.json
cds_dojson/schemas/records/video-v1.0.0.json
cds_dojson/schemas/records/video_src-v1.0.0.json

schemas: duplicated type on project deposit schema, add _project_id in video

---

RELEASE-NOTES.rst

Signed-off-by: Harris Tzovanakis me@drjova.com

release: v0.3.3

---

cds_dojson/marc21/fields/album.py
cds_dojson/marc21/fields/image.py

* Update MARC21 fields due to the latest Library of Congress standard.

marc21: fields update

---

cds_dojson/schemas/deposits/records/project-v1.0.0.json
cds_dojson/schemas/deposits/records/video-v1.0.0.json
cds_dojson/schemas/records/base-v1.0.0.json
cds_dojson/schemas/records/project-v1.0.0.json
cds_dojson/schemas/records/video-v1.0.0.json

schemas: addition of ``doi`` field

---

cds_dojson/schemas/deposits/records/project-v1.0.0.json
cds_dojson/schemas/deposits/records/video-v1.0.0.json
cds_dojson/schemas/records/base-v1.0.0.json
cds_dojson/schemas/records/project-v1.0.0.json
cds_dojson/schemas/records/project_src-v1.0.0.json
cds_dojson/schemas/records/video-v1.0.0.json
cds_dojson/schemas/records/video_src-v1.0.0.json

* Adds `category` and `type` field to project schema.

schemas: category and type of project

---

cds_dojson/schemas/deposits/records/video-v1.0.0.json

schemas: categoty,type deposit video not required

---

cds_dojson/schemas/deposits/records/project-v1.0.0.json
cds_dojson/schemas/deposits/records/video-v1.0.0.json

deposit: revert required fields

---

.travis.yml
cds_dojson/schemas/deposits/records/video-v1.0.0.json
cds_dojson/schemas/records/video-v1.0.0.json
cds_dojson/schemas/records/video_src-v1.0.0.json

video: featured field addition

---

cds_dojson/schemas/deposits/records/project-v1.0.0.json
cds_dojson/schemas/deposits/records/video-v1.0.0.json
cds_dojson/schemas/records/base-v1.0.0.json
cds_dojson/schemas/records/project-v1.0.0.json
cds_dojson/schemas/records/video-v1.0.0.json

* Fixes License field . (addresses CERNDocumentServer/cds#422)

schemas: fix license field

---

cds_dojson/schemas/deposits/records/project-v1.0.0.json
cds_dojson/schemas/deposits/records/video-v1.0.0.json
cds_dojson/schemas/records/base-v1.0.0.json
cds_dojson/schemas/records/project-v1.0.0.json
cds_dojson/schemas/records/project_src-v1.0.0.json
cds_dojson/schemas/records/video-v1.0.0.json
cds_dojson/schemas/records/video_src-v1.0.0.json

schemas: uniform language field

---

cds_dojson/schemas/deposits/records/video-v1.0.0.json
cds_dojson/schemas/records/video-v1.0.0.json
cds_dojson/schemas/records/video_src-v1.0.0.json

* Adds human-readable time duration on the video record schema.

video: duration field addition

---

cds_dojson/schemas/deposits/records/project-v1.0.0.json
cds_dojson/schemas/deposits/records/video-v1.0.0.json
cds_dojson/schemas/records/project-v1.0.0.json
cds_dojson/schemas/records/project_src-v1.0.0.json
cds_dojson/schemas/records/video-v1.0.0.json
cds_dojson/schemas/records/video_src-v1.0.0.json

* Merges translation fields for ``title`` and ``description``. (closes #50)

schemas: merge of translation fields

---

cds_dojson/schemas/deposits/records/project-v1.0.0.json
cds_dojson/schemas/deposits/records/video-v1.0.0.json
cds_dojson/schemas/records/base-v1.0.0.json
cds_dojson/schemas/records/project-v1.0.0.json
cds_dojson/schemas/records/video-v1.0.0.json

schemas: publication_date field addition on base

---

cds_dojson/schemas/deposits/records/project-v1.0.0.json
cds_dojson/schemas/deposits/records/video-v1.0.0.json
cds_dojson/schemas/records/base-v1.0.0.json
cds_dojson/schemas/records/project-v1.0.0.json
cds_dojson/schemas/records/video-v1.0.0.json

Required by https://github.com/CERNDocumentServer/cds/pull/569

schemas: _access.update field addition

---

cds_dojson/schemas/keywords/keyword-v1.0.0.json

* Keywords schema additon. (addresses CERNDocumentServer/cds#420)

schemas: keywords schema addition

---

cds_dojson/schemas/deposits/records/project-v1.0.0.json
cds_dojson/schemas/deposits/records/video-v1.0.0.json
cds_dojson/schemas/records/base-v1.0.0.json
cds_dojson/schemas/records/project-v1.0.0.json
cds_dojson/schemas/records/video-v1.0.0.json

schemas: keywords as references list

---

cds_dojson/schemas/keywords/keyword-v1.0.0.json

Required for https://github.com/CERNDocumentServer/cds/issues/625

schema: add keyword provenance

---

cds_dojson/schemas/deposits/records/videos/project/project-v1.0.0.json
cds_dojson/schemas/deposits/records/videos/video/video-v1.0.0.json
cds_dojson/schemas/records/base-v1.0.0.json
cds_dojson/schemas/records/videos/project/project-v1.0.0.json
cds_dojson/schemas/records/videos/project/project_src-v1.0.0.json
cds_dojson/schemas/records/videos/video/video-v1.0.0.json
cds_dojson/schemas/records/videos/video/video_src-v1.0.0.json

* Fixes errors thrown by the JSON schema form.
Signed-off-by: Nikos Filippakis <nikolaos.filippakis@cern.ch>

schema: json schema form fix

---

cds_dojson/schemas/deposits/records/videos/project/project-v1.0.0.json
cds_dojson/schemas/deposits/records/videos/video/video-v1.0.0.json
cds_dojson/schemas/records/videos/project/project-v1.0.0.json
cds_dojson/schemas/records/videos/project/project_src-v1.0.0.json
cds_dojson/schemas/records/videos/video/video-v1.0.0.json
cds_dojson/schemas/records/videos/video/video_src-v1.0.0.json

* Requires that project and video records have at least one contributor.
Signed-off-by: Nikos Filippakis <nikolaos.filippakis@cern.ch>

schemas: required contributors for records

---

cds_dojson/schemas/deposits/records/base-v1.0.0.json
cds_dojson/schemas/deposits/records/videos/project/project-v1.0.0.json
cds_dojson/schemas/deposits/records/videos/video/video-v1.0.0.json
cds_dojson/schemas/records/videos/project/project-v1.0.0.json
cds_dojson/schemas/records/videos/project/project_src-v1.0.0.json
cds_dojson/schemas/records/videos/video/video-v1.0.0.json
cds_dojson/schemas/records/videos/video/video_src-v1.0.0.json

global: move metadata and state out of _deposit

---

cds_dojson/marc21/models/videos/__init__.py
cds_dojson/marc21/models/videos/project.py
cds_dojson/marc21/models/videos/video.py
setup.py
tests/fixtures/video.xml
tests/test_matcher.py

Signed-off-by: Ludmila Marian <ludmila.marian@gmail.com>

models: new queries for video and project

---

cds_dojson/marc21/fields/base.py
cds_dojson/marc21/fields/videos/video.py
cds_dojson/schemas/deposits/records/videos/video/video-v1.0.0.json
cds_dojson/schemas/records/definitions-v1.0.0.json
cds_dojson/schemas/records/videos/video/video-v1.0.0.json
tests/test_videos_project.py

schemas: fix typo on medium_standard, copyright only for video

---

cds_dojson/marc21/fields/base.py
cds_dojson/marc21/models/videos/project.py
cds_dojson/marc21/models/videos/video.py
tests/test_base.py
tests/test_videos_project.py
tests/test_videos_video.py

marc21: modification_date removal

---

cds_dojson/marc21/fields/videos/project.py
cds_dojson/marc21/fields/videos/video.py
cds_dojson/marc21/models/videos/project.py
cds_dojson/marc21/models/videos/video.py
pytest.ini
setup.py
tests/test_videos_project.py
tests/test_videos_video.py

* Translates 8567_ fields. (addresses #85)

WIP marc21: translate 8567_ fields

---

cds_dojson/schemas/deposits/records/base-v1.0.0.json
cds_dojson/schemas/deposits/records/videos/project/project-v1.0.0.json
cds_dojson/schemas/deposits/records/videos/video/video-v1.0.0.json
cds_dojson/schemas/records/videos/project/project-v1.0.0.json
cds_dojson/schemas/records/videos/project/project_src-v1.0.0.json
cds_dojson/schemas/records/videos/video/video-v1.0.0.json
cds_dojson/schemas/records/videos/video/video_src-v1.0.0.json

* Adds modified_by field on video and projects.
(addresses CERNDocumentServer/cds#991)

schemas: add modified_by field on video/project

---

cds_dojson/marc21/fields/utils.py

WIP marc21: fix problem with encoding

---

cds_dojson/marc21/fields/base.py
cds_dojson/marc21/fields/videos/video.py
cds_dojson/marc21/models/videos/project.py
cds_dojson/marc21/models/videos/video.py
tests/fixtures/videos_project.xml
tests/fixtures/videos_video.xml
tests/test_videos_project.py
tests/test_videos_video.py

marc21: use 774 u field

---

cds_dojson/marc21/fields/videos/video.py
tests/fixtures/videos_video.xml
tests/test_videos_video.py

marc21: fix poster frames conversion

---

cds_dojson/marc21/fields/utils.py

marc21: fix problem with encoding

---

cds_dojson/marc21/fields/videos/video.py
tests/test_videos_video.py

marc21: set poster frame file name

---

cds_dojson/schemas/deposits/records/videos/project/project-v1.0.0.json
cds_dojson/schemas/records/videos/project/project-v1.0.0.json
cds_dojson/schemas/records/videos/project/project_src-v1.0.0.json

schemas: addition of EOS library path

---

cds_dojson/marc21/models/videos/video.py

Closes https://github.com/CERNDocumentServer/cds-videos/issues/1334

marc21: add bunch of fields to ignore list

---

cds_dojson/marc21/fields/videos/video.py
tests/fixtures/videos_video.xml

videos: improve removal of mediaarchive url

---

cds_dojson/marc21/fields/videos/video.py
tests/fixtures/videos_video.xml

video: ignore ``flv`` and ``wmv`` files

---

cds_dojson/schemas/deposits/records/videos/video/video-v1.0.0.json
cds_dojson/schemas/records/videos/video/video-v1.0.0.json
cds_dojson/schemas/records/videos/video/video_src-v1.0.0.json

Finishes up with https://github.com/CERNDocumentServer/cds-videos/issues/1576

schemas: add Press field to videos

---

MANIFEST.in
cds_dojson/schemas/books/ymls/books-proc-stds.yml
cds_dojson/schemas/books/ymls/elements/acquisition_source.yml
cds_dojson/schemas/books/ymls/elements/additional_subject_categories.yml
cds_dojson/schemas/books/ymls/elements/cds_subject_categories.yml
cds_dojson/schemas/books/ymls/elements/degree_type.yml
cds_dojson/schemas/books/ymls/elements/document_type.yml
cds_dojson/schemas/books/ymls/elements/related_record.yml
cds_dojson/schemas/books/ymls/elements/source.yml
cds_dojson/schemas/books/ymls/elements/sourced_value.yml
cds_dojson/schemas/books/ymls/elements/title.yml
cds_dojson/schemas/books/ymls/elements/url.yml
cds_dojson/schemas/books/ymls/holding.yml
tests/fixtures/books/books_book1.xml
tests/fixtures/books/books_book2.xml

Contains basic schema for books in yml files and example books fixtures for testing

YML Book Schema and fixtures

---

cds_dojson/marc21/fields/books/book.py
cds_dojson/schemas/records/books/book/document-v0.0.1.json
cds_dojson/schemas/records/books/book/document_src-v0.0.1.json
cds_dojson/schemas/records/books/ymls/document_src-v0.0.1.yml
tests/test_books.py

Books fix conference

---

cds_dojson/marc21/models/books/book.py
tests/test_matcher.py

* Updates the query for matching book records
(closes CERNDocumentServer/cds-migrator-kit#19)
Signed-off-by: Ludmila Marian <ludmila.marian@gmail.com>

models: update query for books

---

cds_dojson/marc21/fields/base.py
cds_dojson/marc21/fields/books/book.py
cds_dojson/marc21/fields/videos/base.py
tests/test_books.py

( closes #183 )
To be merged after #189

Ignored rules check

---

cds_dojson/marc21/fields/books/base.py
cds_dojson/marc21/fields/books/utils.py
cds_dojson/schemas/records/books/book/item.json
cds_dojson/schemas/records/books/ymls/item.yml
setup.cfg
tests/test_books.py

* Attempting to extract number of pages
* If any relevant information is found it gets parsed and stored under physical_description
* resolves #184

books: expanding number_of_pages to physical_description

---

tests/fixtures/videos_video.xml
tests/test_videos_project.py
tests/test_videos_video.py

* replaced the email of a person who left CERN and broke the tests

fix: replace invalid email

---

cds_dojson/marc21/fields/books/base.py
tests/test_books.py

books: filter urls based on their origin

---

README.rst
cds_dojson/marc21/fields/base.py
cds_dojson/marc21/fields/books/base.py
cds_dojson/marc21/fields/videos/base.py
cds_dojson/schemas/records/books/book/base-v0.0.1.json
cds_dojson/schemas/records/books/book/document-v0.0.1.json
cds_dojson/schemas/records/books/ymls/base-v0.0.1.yml
tests/test_books.py

* Raise `UnexpectedValue` for unhandled `document_types`
* Rename keyword `source` to `provenance`
* Closes #168

books: check conditional values

---

cds_dojson/marc21/fields/books/base.py
cds_dojson/marc21/fields/books/book.py
cds_dojson/marc21/fields/books/standard.py
cds_dojson/marc21/models/books/base.py
tests/test_books.py

rules: updated ignored keys, subject_classification, title

---

cds_dojson/marc21/models/books/multipart.py
cds_dojson/marc21/models/books/serial.py
cds_dojson/schemas/records/books/book/base-v0.0.1.json
cds_dojson/schemas/records/books/book/document-v0.0.1.json
cds_dojson/schemas/records/books/book/document_src-v0.0.1.json
cds_dojson/schemas/records/books/book/eitem-v0.0.1.json
cds_dojson/schemas/records/books/book/elements/file.json
cds_dojson/schemas/records/books/book/item-v0.0.1.json
cds_dojson/schemas/records/books/book/keyword-v0.0.1.json
cds_dojson/schemas/records/books/book/series-v.0.0.1.json
cds_dojson/schemas/records/books/ymls/base-v0.0.1.yml
cds_dojson/schemas/records/books/ymls/document_src-v0.0.1.yml
cds_dojson/schemas/records/books/ymls/eitem-v0.0.1.yml
cds_dojson/schemas/records/books/ymls/elements/file.yml
cds_dojson/schemas/records/books/ymls/item-v0.0.1.yml
cds_dojson/schemas/records/books/ymls/keyword-v0.0.1.yml
cds_dojson/schemas/records/books/ymls/series-v.0.0.1.yml
tests/test_cli.py
tests/test_series.py

* added new schemas per record type
(to be used in CDS-books)
needs verification and comments
( closes #224 )

New types schemas

---

cds_dojson/schemas/records/books/book/eitem-v0.0.1.json
cds_dojson/schemas/records/books/book/item-v0.0.1.json
cds_dojson/schemas/records/books/ymls/eitem-v0.0.1.yml
cds_dojson/schemas/records/books/ymls/item-v0.0.1.yml
tests/test_cli.py

remove DOIs from item level

---

cds_dojson/schemas/records/books/book/eitem-v0.0.1.json
cds_dojson/schemas/records/books/book/item-v0.0.1.json
cds_dojson/schemas/records/books/ymls/eitem-v0.0.1.yml
cds_dojson/schemas/records/books/ymls/item-v0.0.1.yml

schemas: clean Eitem and Item schemas

---

cds_dojson/marc21/fields/books/base.py
cds_dojson/marc21/fields/books/multipart.py
cds_dojson/marc21/fields/books/utils.py
cds_dojson/marc21/models/books/book.py
cds_dojson/marc21/models/books/serial.py
tests/test_books.py
tests/test_utils.py

document: implement rule 088__ barcodes

---

cds_dojson/marc21/fields/books/multipart.py
tests/test_series.py

Implement 020__b

---

.travis.yml
cds_dojson/marc21/fields/books/base.py
cds_dojson/marc21/fields/books/book.py
cds_dojson/marc21/fields/books/multipart.py
cds_dojson/marc21/fields/books/serial.py
cds_dojson/marc21/fields/books/standard.py
cds_dojson/marc21/fields/books/utils.py
cds_dojson/marc21/fields/books/values_mapping.py
cds_dojson/marc21/fields/utils.py
cds_dojson/marc21/models/books/base.py
cds_dojson/marc21/models/books/book.py
tests/test_books.py
tests/test_series.py
tests/test_standard.py

* changed all the identifiers to common structure
* removed all the emails
* removed funding info
* restructurised title objects
When reviewing please ask for spreadsheet with migration data

migration: updated schema changes

---

cds_dojson/marc21/fields/books/base.py
cds_dojson/marc21/fields/books/book.py
cds_dojson/marc21/fields/books/multipart.py
cds_dojson/marc21/fields/books/serial.py
cds_dojson/marc21/models/books/book.py
cds_dojson/marc21/models/books/multipart.py
cds_dojson/marc21/models/books/serial.py
cds_dojson/marc21/models/books/standard.py
tests/test_books.py
tests/test_matcher.py
tests/test_series.py

* fixed dates and pages types in the output

books: fixed record match queries

---

cds_dojson/marc21/fields/books/base.py
cds_dojson/marc21/fields/books/journal.py
cds_dojson/marc21/fields/books/serial.py
cds_dojson/marc21/fields/utils.py
cds_dojson/marc21/models/books/base.py
cds_dojson/marc21/models/books/journal.py
tests/test_books.py
tests/test_journals.py

* fix replace in strings util function
* ignore 695 field
* ignore 084__2 084__a
* ignore arXiv category
* ignore inspire CNUM on publications
* ignore redundant fields from journals

books: rules update

---

cds_dojson/marc21/fields/books/base.py
run-tests.sh
tests/test_books.py

* Adds rule to translate the
standard_status field
* closes #257

document: Adds extension fields rules

---

cds_dojson/marc21/fields/books/base.py

books: add eproceedings to the urls

---

.github/workflows/tests.yml
MANIFEST.in
cds_dojson/marc21/fields/videos/video.py
cds_dojson/matcher.py
cds_dojson/overdo.py
cds_dojson/utils.py

* improves performance drastically

global: replace pkg_resources with importlib
