CERNDocumentServer/cds-dojson

cds_dojson/cli.py
cds_dojson/schemas/deposits/records/project-v1.0.0.json
cds_dojson/schemas/deposits/records/project_src-v1.0.0.json
cds_dojson/schemas/deposits/records/video-v1.0.0.json
cds_dojson/schemas/deposits/records/video_src-v1.0.0.json
cds_dojson/schemas/records/base-v1.0.0.json
cds_dojson/schemas/records/project-v1.0.0.json
cds_dojson/schemas/records/project_src-v1.0.0.json
cds_dojson/schemas/records/video-v1.0.0.json
cds_dojson/schemas/records/video_src-v1.0.0.json
cds_dojson/schemas/tranform.py
setup.py
tests/test_cds_dojson_video.py
tests/test_cli.py
tests/testutils.py

* Adds new version of video and project schemas with resolved references
and compiled `allOf` keys. (closes CERNDocumentServer/cds#214)
* New `cds-dojson compile_schema` CLI to help building the compiled
schemas.
* Adds `_deposit` key to base

schemas: complied video schemas

---

cds_dojson/schemas/deposits/records/project-v1.0.0.json
cds_dojson/schemas/deposits/records/video-v1.0.0.json
cds_dojson/schemas/records/base-v1.0.0.json
cds_dojson/schemas/records/project-v1.0.0.json
cds_dojson/schemas/records/video-v1.0.0.json

* Adds `type` to `keywords.items` for compatability with SchemaForm.
Signed-off-by: Sourabh Lal sourabh.lal@cern.ch

schemas: fix `keywords` key in project

---

cds_dojson/schemas/deposits/records/project-v1.0.0.json
cds_dojson/schemas/deposits/records/project_src-v1.0.0.json
cds_dojson/schemas/deposits/records/video-v1.0.0.json
cds_dojson/schemas/deposits/records/video_src-v1.0.0.json
cds_dojson/schemas/records/project-v1.0.0.json
cds_dojson/schemas/records/project_src-v1.0.0.json
cds_dojson/schemas/records/video-v1.0.0.json
cds_dojson/schemas/records/video_src-v1.0.0.json

schemas: addition of `extracted_metadata`

---

cds_dojson/schemas/deposits/records/project-v1.0.0.json
cds_dojson/schemas/deposits/records/video-v1.0.0.json
cds_dojson/schemas/records/base-v1.0.0.json
cds_dojson/schemas/records/project-v1.0.0.json
cds_dojson/schemas/records/video-v1.0.0.json

* Adds `report_number` field to `base`, `project` and `video` schemas.

schemas: report number addition

---

cds_dojson/schemas/records/project-v1.0.0.json
cds_dojson/schemas/records/project_src-v1.0.0.json
cds_dojson/schemas/records/video-v1.0.0.json
cds_dojson/schemas/records/video_src-v1.0.0.json

* Video or project schemas for records have `report_number` as a
required field.

schemas: require report numbers

---

cds_dojson/schemas/deposits/records/project-v1.0.0.json

* Removes previously required fields of project deposit
(`date`, `category`, `type`).
commit dc9cf302aa671b22c328c37f6e2d94d2358f9b72

schemas: remove required fields of project deposit

---

cds_dojson/schemas/records/video-v1.0.0.json
cds_dojson/schemas/records/video_src-v1.0.0.json

* Makes the `duration` field required for video records. (closes #47)
* Depends on #46.

video: duration field required

---

cds_dojson/schemas/deposits/records/project-v1.0.0.json
cds_dojson/schemas/deposits/records/video-v1.0.0.json
cds_dojson/schemas/records/base-v1.0.0.json
cds_dojson/schemas/records/project-v1.0.0.json
cds_dojson/schemas/records/video-v1.0.0.json
cds_dojson/schemas/records/video_src-v1.0.0.json

* Removes `.` from schema description. (closes CERNDocumentServer/cds#704)

schemas: remove `.` from description

---

cds_dojson/schemas/deposits/records/videos/video/video-v1.0.0.json
cds_dojson/schemas/deposits/records/videos/video/video_src-v1.0.0.json
cds_dojson/schemas/records/videos/video/video-v1.0.0.json
cds_dojson/schemas/records/videos/video/video_src-v1.0.0.json

* Adds a `vr` flag to videos, in order to selectively enable VR
capabilities in THEOplayer.

video: vr field addition

---

cds_dojson/utils.py
tests/test_utils.py

* Fixes MementoDict to key a list of values when the key has more that value and is initialized with a tuple.

utils: fix repteable values MementoDict

---

cds_dojson/marc21/fields/videos/utils.py
cds_dojson/marc21/fields/videos/video.py
cds_dojson/marc21/models/videos/video.py
setup.py
tests/fixtures/videos_video.xml
tests/test_videos_video.py

* Adds function to translate language code.
* Adds oaiset fields. (closes #78)

marc21: translate language isocode

---

cds_dojson/marc21/fields/base.py

* Fixes a typo in several records which mistakes subfield `9` with
subfield `g`.

marc21: add 6531_g translation

---

cds_dojson/marc21/fields/utils.py

* Ignore contributor field, if there is no $a subfield.

fields: ignore empty contributors

---

cds_dojson/marc21/fields/videos/video.py
cds_dojson/schemas/deposits/records/videos/project/project-v1.0.0.json
cds_dojson/schemas/deposits/records/videos/video/video-v1.0.0.json
cds_dojson/schemas/records/definitions-v1.0.0.json
cds_dojson/schemas/records/videos/project/project-v1.0.0.json
cds_dojson/schemas/records/videos/project/project_src-v1.0.0.json
cds_dojson/schemas/records/videos/video/video-v1.0.0.json
cds_dojson/schemas/records/videos/video/video_src-v1.0.0.json
tests/test_videos_video.py

* Fixes internal_note fields when 595 has multiple values
* Add new field internal_categories to keep the possible future
communities stored inside 595. (addresses CERNDocumentServer/cds-videos#1576)

marc21: fix internal_* fields

---

cds_dojson/marc21/fields/books/book.py
cds_dojson/marc21/fields/books/values_mapping.py
cds_dojson/schemas/records/books/ymls/base-v0.0.1.yml
tests/test_books.py

* Adds new lists for external identifiers in order to determine
which values should be allowed and which to be ignored.
(closes #167)
Signed-off-by: Ludmila Marian <ludmila.marian@gmail.com>

marc21: fix rule for external identifiers (035)

---

README.rst
cds_dojson/marc21/fields/books/base.py
cds_dojson/marc21/fields/books/book.py
cds_dojson/schemas/records/books/book/base-v0.0.1.json
cds_dojson/schemas/records/books/book/document-v0.0.1.json
cds_dojson/schemas/records/books/book/elements/title.json
cds_dojson/schemas/records/books/ymls/base-v0.0.1.yml
cds_dojson/schemas/records/books/ymls/elements/title.yml
tests/test_books.py
tests/test_standard.py

* Remapped field 245 to an object instead of a list.
* Raises an `UnexpectedValue` exception if there is a duplicate entry for 245
* Mapped 246 to alternative titles for books
* The relevant tests for all above
* Added instructions on how to build schemas to `README.rst`
* Resolves #192

field 245 as title and field 246 as alternative titles for books

---

cds_dojson/marc21/fields/books/base.py
tests/test_books.py

* for field 695__ when subfield 9 is LANL EDS then subfield a is stored in: arxiv_eprints/categories
* resolves #198

fields: rule for 695__

---

cds_dojson/marc21/fields/books/book.py
cds_dojson/marc21/fields/books/multipart.py
cds_dojson/marc21/fields/books/utils.py
cds_dojson/marc21/fields/utils.py
tests/test_books.py
tests/test_series.py
tests/test_utils.py

* Also parse volume numbers in `020__`
* Raise exception if an invalid role was found
* Fix bugs causing `document` rectype to fail
Closes #240

multipart: improved volume number parser

---

cds_dojson/marc21/fields/books/base.py
cds_dojson/marc21/fields/books/book.py
cds_dojson/marc21/fields/books/multipart.py
cds_dojson/marc21/fields/utils.py
cds_dojson/marc21/models/books/base.py
cds_dojson/marc21/models/books/book.py
cds_dojson/marc21/models/books/standard.py
tests/test_books.py
tests/test_standard.py

* Store serials in `_migration.serials`
* Store keywords in `_migration.keywords`
* Change `role` to `roles` and store the value in lowercase
* Use `has_keyword`, `is_multipart` and `has_serial` to indicate if the record has any keywords, multipart or serials
* Implemented volumes for `document` record type
Closes #238

books: updates to serials and multiparts

---

cds_dojson/marc21/fields/books/base.py
cds_dojson/marc21/fields/books/book.py
cds_dojson/marc21/fields/books/multipart.py
cds_dojson/marc21/fields/books/serial.py
cds_dojson/marc21/fields/books/standard.py
cds_dojson/marc21/fields/books/utils.py
cds_dojson/marc21/models/books/base.py
cds_dojson/marc21/models/books/book.py
cds_dojson/marc21/models/books/multipart.py
cds_dojson/marc21/models/books/serial.py
cds_dojson/marc21/models/books/standard.py
run-tests.sh
tests/test_books.py
tests/test_matcher.py
tests/test_series.py
tests/test_utils.py

* add ignored keys
* tweak record match queries

books: fixed arXiv eprints and collaboration rules

---

cds_dojson/marc21/fields/books/base.py
cds_dojson/marc21/fields/books/journal.py
cds_dojson/marc21/fields/books/values_mapping.py
cds_dojson/marc21/fields/utils.py
tests/test_books.py
tests/test_journals.py

Closes partially CERNDocumentServer/cds-ils#154
- remove `ed.` from editions
- fix broken `language` and `author.roles` field

Field fixes
